using MCM.Abstractions.Attributes;
using MCM.Abstractions.Attributes.v2;
using MCM.Abstractions.Settings.Base;
using MCM.Abstractions.Settings.Base.Global;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using TaleWorlds.Localization;

namespace IronBank
{
    public interface ISettingsProvider
    {
        event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        float InterestRates { get; set; }

        float TaxIn { get; set; }

        float TaxOut { get; set; }

        float ReinvestmentRate { get; set; }
    }

    public class HardcodedSettings : ISettingsProvider
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public float InterestRates { get; set; } = 0.002f;

        public float TaxIn { get; set; } = 0.025f;

        public float TaxOut { get; set; } = 0.035f;

        public float ReinvestmentRate { get; set; } = 0.2f;
    }

    public class Settings : AttributeGlobalSettings<Settings>, ISettingsProvider
    {
        public override string Id => "IronBank";

        public override string DisplayName => new TextObject(
            "{=Settings_Name}Iron Bank {VERSION}",
            new Dictionary<string, TextObject>
            {
                { "VERSION", new TextObject(typeof(Settings).Assembly.GetName().Version.ToString(3)) }
            }
        ).ToString();

        public override string FolderName { get; } = "IronBank";

        public override string FormatType { get; } = "json2";

        public override IDictionary<string, Func<BaseSettings>> GetAvailablePresets()
        {
            var basePresets = base.GetAvailablePresets(); // include the 'Default' preset that MCM provides
            basePresets.Add("Realistic", () => new Settings()
            {
                InterestRates = 0.002f,
                TaxIn = 0.025f,
                TaxOut = 0.035f,
                ReinvestmentRate = 0.2f
            });
            basePresets.Add("Easy", () => new Settings()
            {
                InterestRates = 0.008f,
                TaxIn = 0.015f,
                TaxOut = 0.015f,
                ReinvestmentRate = 0.2f
            });
            basePresets.Add("Very Easy", () => new Settings()
            {
                InterestRates = 0.01f,
                TaxIn = 0.05f,
                TaxOut = 0.05f,
                ReinvestmentRate = 0.2f
            });
            return basePresets;
        }

        [SettingPropertyGroup("{=IronBank_General}General")]
        [SettingPropertyFloatingInteger(
            "{=IronBank_Interests}Interest rate",
            minValue: 0.0f, maxValue: 0.05f, valueFormat: "P", RequireRestart = false,
            HintText = "Daily interest rate generated by your account."
        )]
        public float InterestRates { get; set; }

        [SettingPropertyGroup("{=IronBank_General}General")]
        [SettingPropertyFloatingInteger(
            "{=IronBank_Interests}Taxes on deposit",
            minValue: 0.0f, maxValue: 0.10f, valueFormat: "P", RequireRestart = false,
            HintText = "A tax applyed by the bank on every deposit."
        )]
        public float TaxIn { get; set; }

        [SettingPropertyGroup("{=IronBank_General}General")]
        [SettingPropertyFloatingInteger(
            "{=IronBank_Interests}Taxes on withdraw",
            minValue: 0.0f, maxValue: 0.10f, valueFormat: "P", RequireRestart = false,
            HintText = "A tax applyed by the bank on every widthdraw."
        )]
        public float TaxOut { get; set; }

        [SettingPropertyGroup("{=IronBank_General}General")]
        [SettingPropertyFloatingInteger(
            "{=IronBank_Interests}Reinvestment rate",
            minValue: 0f, maxValue: 1f, valueFormat: "P", RequireRestart = false,
            HintText = "Rate of interests to deposit in bank account."
        )]
        public float ReinvestmentRate { get; set; }
    }
}
